version: '3.4'

services:
  #catalogservice.api:
  #  image: ${DOCKER_REGISTRY-}catalogserviceapi
  #  build:
  #    context: .
  #    dockerfile: src/Services/CatalogService/CatalogService.Api/Dockerfile


  s_rabbitmq:
    container_name: c_rabbitmq
    image: rabbitmq:3-management
    

  s_consul:
    container_name: c_consul
    image: consul:1.15

